### PR TITLE
Create sh_file

### PR DESCRIPTION
**Pull request by SHagelin**
testing git pull request. nothing to use in the new file

### CODE REVIEW

**Comment by mridal** [comment]
Hmm, I don't know. 
Ok, go ahead then.

**Review by uandrae — CHANGES_REQUESTED** [review]
Swedish please

**Review by mridal — COMMENTED** [review]
Amen, vaf!
Skicka in den bara!

**Comment by SHagelin** [comment]
now in Swedish. :D

**Review by roelstappers — APPROVED** [review]

**Review by mridal — APPROVED** [review]

**Pull request merged**
